<a href="https://colab.research.google.com/github/NewbieZilani/MSc-Explainable-AI/blob/main/01_Pandas/Pandas_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import files

uploaded = files.upload()

Saving italy-covid-daywise.csv to italy-covid-daywise.csv

In [17]:
covid_df = pd.read_csv("italy-covid-daywise.csv")
covid_df.head()
covid_df.tail()
covid_df.shape

(248, 4)

In [20]:
type(covid_df)

pandas.core.frame.DataFrame

In [18]:
covid_df.columns

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='object')

In [16]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        248 non-null    object
 1   new_cases   248 non-null    float64
 2   new_deaths  248 non-null    float64
 3   new_tests   135 non-null    float64
dtypes: float64(3), object(1)
memory usage: 7.9+ KB

In [21]:
covid_df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

In [15]:
# To find missing values
covid_df.isnull().sum()

date            0
new_cases       0
new_deaths      0
new_tests     113
dtype: int64

In [19]:
# Statistical summary
covid_df.describe()

         new_cases  new_deaths     new_tests
count   248.000000  248.000000    135.000000
mean   1094.818548  143.133065  31699.674074
std    1554.508002  227.105538  11622.209757
min    -148.000000  -31.000000   7841.000000
25%     123.000000    3.000000  25259.000000
50%     342.000000   17.000000  29545.000000
75%    1371.750000  175.250000  37711.000000
max    6557.000000  971.000000  95273.000000

In [23]:
covid_df["date"]=pd.to_datetime(covid_df["date"])
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        248 non-null    datetime64[ns]
 1   new_cases   248 non-null    float64
 2   new_deaths  248 non-null    float64
 3   new_tests   135 non-null    float64
dtypes: datetime64[ns](1), float64(3)
memory usage: 7.9 KB

In [25]:
totalcases=covid_df["new_cases"].sum()
print(totalcases)

271515.0

In [28]:
totalDeath=covid_df["new_deaths"].sum()
print(totalDeath)

35497.0

In [29]:
# Maximum death in a single day
covid_df.loc[covid_df["new_deaths"].idxmax()]

date          2020-03-28 00:00:00
new_cases                  5959.0
new_deaths                  971.0
new_tests                     NaN
Name: 88, dtype: object

In [37]:
# highest death in a single day without all row
covid_df["new_deaths"].max()

971.0

In [30]:
# Maximum cases in a single day
covid_df.loc[covid_df["new_cases"].idxmax()]

date          2020-03-22 00:00:00
new_cases                  6557.0
new_deaths                  795.0
new_tests                     NaN
Name: 82, dtype: object

In [38]:
covid_df["new_cases"].max()

6557.0

In [31]:
# top 10 day when new cases was maximum
covid_df.sort_values("new_cases", ascending=False).head(10)

         date  new_cases  new_deaths  new_tests
82 2020-03-22     6557.0       795.0        NaN
87 2020-03-27     6153.0       660.0        NaN
81 2020-03-21     5986.0       625.0        NaN
89 2020-03-29     5974.0       887.0        NaN
88 2020-03-28     5959.0       971.0        NaN
83 2020-03-23     5560.0       649.0        NaN
80 2020-03-20     5322.0       429.0        NaN
85 2020-03-25     5249.0       743.0        NaN
90 2020-03-30     5217.0       758.0        NaN
86 2020-03-26     5210.0       685.0        NaN

In [33]:
# top 10 day when new deaths was maximum
covid_df.sort_values("new_deaths", ascending=False).head(10)

         date  new_cases  new_deaths  new_tests
88 2020-03-28     5959.0       971.0        NaN
89 2020-03-29     5974.0       887.0        NaN
92 2020-04-01     4053.0       839.0        NaN
91 2020-03-31     4050.0       810.0        NaN
82 2020-03-22     6557.0       795.0        NaN
95 2020-04-04     4585.0       764.0        NaN
94 2020-04-03     4668.0       760.0        NaN
90 2020-03-30     5217.0       758.0        NaN
85 2020-03-25     5249.0       743.0        NaN
93 2020-04-02     4782.0       727.0        NaN

In [36]:
# total cases in a month
covid_df["month"]=covid_df["date"].dt.month
covid_df.groupby("month")["new_cases"].sum()

month
1          3.0
2        885.0
3     100851.0
4     101852.0
5      29073.0
6       7772.0
7       6722.0
8      21060.0
9       3297.0
12         0.0
Name: new_cases, dtype: float64

In [41]:
covid_df.loc[covid_df["date"] == "2020-03-28", "new_deaths"]

88    971.0
Name: new_deaths, dtype: float64

In [42]:
from numpy import cov
covid_df.loc[covid_df["date"] == "2020-03-27", "new_deaths"].iloc[0]

np.float64(660.0)

In [45]:
date = input("Enter date (YYYY-MM-DD): ")

deaths = covid_df.loc[covid_df["date"] == date, "new_deaths"]

if not deaths.empty:
    print(f"Deaths on {date}: {deaths.iloc[0]}")
else:
    print("Date not found.")

Enter date (YYYY-MM-DD): 2020-03-28
Deaths on 2020-03-28: 971.0